### ISSUE TITLE
Secret Doors textures messed up

### ISSUE THREAD

**Issue by gallowglass** [JasonMcRay/InfiTech-1.7#142]
![2015-02-14_15 27 18](https://cloud.githubusercontent.com/assets/7349888/6200946/23d0d0ba-b45e-11e4-9936-208b10845c30.png)

**Comment by JasonMcRay** [comment]
In theory it should be fixed in v2.1.3 - I am unable to replicate this in my dev instance.
Please try it out, when the version is out on the launcher.

**Comment by gallowglass** [comment]
Yep, 2.1.3 fixed it.  Enderio conduits still have a texture issue though.

**Comment by JasonMcRay** [comment]
Yea. Tterag and crazypants are forgetting about it :)
